# Generated by Django 5.0.14 on 2026-06-24 16:03

import django.db.models.deletion
import payments.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgeros', '0006_ledgerosconnectionsettings_host_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type_priority', models.JSONField(blank=True, default=payments.models.default_charge_type_priority, help_text='Global charge allocation priority list for MVP.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment workflow settings',
            },
        ),
        migrations.CreateModel(
            name='SecurityDepositEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('required', 'Required'), ('received', 'Received'), ('deducted', 'Deducted'), ('refunded', 'Refunded')], max_length=20)),
                ('event_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sync_pending', 'Sync pending'), ('synced', 'Synced'), ('sync_failed', 'Sync failed'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_events', to='ledgeros.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_events', to='ledgeros.property')),
                ('sync_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_deposit_event', to='ledgeros.ledgerossyncrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_events', to='ledgeros.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_events', to='ledgeros.unit')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('ach_manual', 'ACH manual'), ('card_manual', 'Card manual'), ('other', 'Other')], max_length=32)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('allocated', 'Allocated'), ('ready_to_sync', 'Ready to sync'), ('sync_pending', 'Sync pending'), ('synced', 'Synced'), ('sync_failed', 'Sync failed'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_payments', to='ledgeros.property')),
                ('sync_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_payment', to='ledgeros.ledgerossyncrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_payments', to='ledgeros.tenant')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TenantPaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='ledgeros.tenantcharge')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='payments.tenantpayment')),
                ('sync_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_payment_application', to='ledgeros.ledgerossyncrecord')),
            ],
            options={
                'ordering': ['charge__due_date', 'charge__charge_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantpaymentapplication',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='uniq_tenant_payment_application_charge'),
        ),
    ]
