# Generated by Django 5.0.14 on 2026-06-26 22:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgeros', '0006_ledgerosconnectionsettings_host_header'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DebtServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('loan_liability_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('interest_expense_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sync_pending', 'Sync pending'), ('synced', 'Synced'), ('sync_failed', 'Sync failed'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_service_payments', to='ledgeros.property')),
                ('sync_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_service_payment', to='ledgeros.ledgerossyncrecord')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_service_payments', to='payments.vendor')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expense_category', models.CharField(choices=[('repairs_and_maintenance', 'Repairs and maintenance'), ('utilities', 'Utilities'), ('management_fee', 'Management fee'), ('other', 'Other')], max_length=64)),
                ('repair_notes', models.TextField(blank=True, default='')),
                ('tenant_chargeable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sync_pending', 'Sync pending'), ('synced', 'Synced'), ('sync_failed', 'Sync failed'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('maintenance_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='payments.maintenancecategory')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='ledgeros.property')),
                ('sync_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bill', to='ledgeros.ledgerossyncrecord')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='ledgeros.unit')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='payments.vendor')),
            ],
            options={
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('manual_check', 'Manual check'), ('ach_manual', 'ACH manual'), ('credit_card', 'Credit card'), ('cash', 'Cash'), ('other', 'Other')], max_length=32)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('credit_card_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.TextField(blank=True, default='')),
                ('check_number', models.CharField(blank=True, max_length=64, null=True)),
                ('check_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending_print', 'Pending print'), ('printed', 'Printed'), ('voided', 'Voided')], default='not_applicable', max_length=20)),
                ('is_credit_card_payoff', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sync_pending', 'Sync pending'), ('synced', 'Synced'), ('sync_failed', 'Sync failed'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('sync_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payment', to='ledgeros.ledgerossyncrecord')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.vendor')),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='payments.vendorbill')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
