# Generated by Django 5.0.14 on 2026-07-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_maintenancecategory_vendor_debtservicepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtservicepayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_sync', 'Ready to sync'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='securitydepositevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_sync', 'Ready to sync'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('allocated', 'Allocated'), ('ready_to_sync', 'Ready to sync'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_sync', 'Ready to sync'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_sync', 'Ready to sync'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
    ]
