# Generated by Django 5.0.14 on 2026-07-06 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_debtservicepayment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='sync_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='ledgeros.ledgerossyncrecord'),
        ),
    ]
