from django.urls import path

from payments.views import (
    DebtServicePaymentCreateView,
    DebtServicePaymentDetailView,
    DebtServicePaymentListView,
    DebtServicePaymentUpdateView,
    MaintenanceCategoryCreateView,
    MaintenanceCategoryListView,
    MaintenanceCategoryUpdateView,
    TenantInvoiceDetailView,
    TenantInvoiceListView,
    SecurityDepositEventCreateView,
    SecurityDepositEventDetailView,
    SecurityDepositEventUpdateView,
    SecurityDepositEventListView,
    TenantPaymentCreateView,
    TenantPaymentDetailView,
    TenantPaymentUpdateView,
    TenantPaymentListView,
    PaymentsLandingView,
    VendorBillCreateView,
    VendorBillDetailView,
    VendorBillListView,
    VendorBillUpdateView,
    VendorCreateView,
    VendorListView,
    VendorUpdateView,
    VendorPaymentCreateView,
    VendorPaymentDetailView,
    VendorPaymentListView,
    VendorPaymentUpdateView,
)


urlpatterns = [
    path("", PaymentsLandingView.as_view(), name="payments-home"),
    path("vendors/", VendorListView.as_view(), name="vendor-list"),
    path("vendors/add/", VendorCreateView.as_view(), name="vendor-create"),
    path("vendors/<int:pk>/edit/", VendorUpdateView.as_view(), name="vendor-edit"),
    path("maintenance-categories/", MaintenanceCategoryListView.as_view(), name="maintenance-category-list"),
    path("maintenance-categories/add/", MaintenanceCategoryCreateView.as_view(), name="maintenance-category-create"),
    path("maintenance-categories/<int:pk>/edit/", MaintenanceCategoryUpdateView.as_view(), name="maintenance-category-edit"),
    path("vendor-bills/", VendorBillListView.as_view(), name="vendor-bill-list"),
    path("vendor-bills/add/", VendorBillCreateView.as_view(), name="vendor-bill-create"),
    path("vendor-bills/<int:pk>/", VendorBillDetailView.as_view(), name="vendor-bill-detail"),
    path("vendor-bills/<int:pk>/edit/", VendorBillUpdateView.as_view(), name="vendor-bill-edit"),
    path("vendor-payments/", VendorPaymentListView.as_view(), name="vendor-payment-list"),
    path("vendor-payments/add/", VendorPaymentCreateView.as_view(), name="vendor-payment-create"),
    path("vendor-payments/<int:pk>/", VendorPaymentDetailView.as_view(), name="vendor-payment-detail"),
    path("vendor-payments/<int:pk>/edit/", VendorPaymentUpdateView.as_view(), name="vendor-payment-edit"),
    path("debt-service-payments/", DebtServicePaymentListView.as_view(), name="debt-service-payment-list"),
    path("debt-service-payments/add/", DebtServicePaymentCreateView.as_view(), name="debt-service-payment-create"),
    path("debt-service-payments/<int:pk>/", DebtServicePaymentDetailView.as_view(), name="debt-service-payment-detail"),
    path("debt-service-payments/<int:pk>/edit/", DebtServicePaymentUpdateView.as_view(), name="debt-service-payment-edit"),
    path("invoices/", TenantInvoiceListView.as_view(), name="invoice-list"),
    path("invoices/<int:pk>/", TenantInvoiceDetailView.as_view(), name="invoice-detail"),
    path("tenant-payments/", TenantPaymentListView.as_view(), name="tenant-payment-list"),
    path("tenant-payments/add/", TenantPaymentCreateView.as_view(), name="tenant-payment-create"),
    path("tenant-payments/<int:pk>/", TenantPaymentDetailView.as_view(), name="tenant-payment-detail"),
    path("tenant-payments/<int:pk>/edit/", TenantPaymentUpdateView.as_view(), name="tenant-payment-edit"),
    path("security-deposits/", SecurityDepositEventListView.as_view(), name="security-deposit-list"),
    path("security-deposits/add/", SecurityDepositEventCreateView.as_view(), name="security-deposit-create"),
    path("security-deposits/<int:pk>/", SecurityDepositEventDetailView.as_view(), name="security-deposit-detail"),
    path("security-deposits/<int:pk>/edit/", SecurityDepositEventUpdateView.as_view(), name="security-deposit-edit"),
]
