from django.urls import path

from reports.views import (
    DelinquencyReportView,
    OwnerContributionDistributionArchiveView,
    OwnerContributionDistributionCreateView,
    OwnerContributionDistributionDetailView,
    OwnerContributionDistributionListView,
    OwnerContributionDistributionUpdateView,
    OwnerStatementReportView,
    OwnerPendingSyncReportView,
    OwnerStatementExportView,
    OwnerStatementView,
    ReportsLandingView,
    RentRollReportView,
    SecurityDepositLedgerReportView,
    TenantLedgerReportView,
    PropertyIncomeExpenseReportView,
    ManagementFeeExpenseSummaryReportView,
    MaintenanceExpenseSummaryReportView,
    LedgerOSTrialBalanceReportView,
    LedgerOSProfitAndLossReportView,
    LedgerOSBalanceSheetReportView,
    LedgerOSPeriodSummaryReportView,
    LedgerOSTaxSummaryReportView,
    LedgerOSChartOfAccountsReportView,
    LedgerOSInvoiceStatusReportView,
    LedgerOSBillStatusReportView,
    LedgerOSPaymentStatusReportView,
    LedgerOSBankBalancesReportView,
    LedgerOSReconciliationStatusReportView,
    LedgerOSAuditDrilldownReportView,
)


urlpatterns = [
    path("", ReportsLandingView.as_view(), name="reports-home"),
    path("owner-activities/", OwnerContributionDistributionListView.as_view(), name="owner-activity-list"),
    path("owner-activities/add/", OwnerContributionDistributionCreateView.as_view(), name="owner-activity-create"),
    path("owner-activities/<int:pk>/", OwnerContributionDistributionDetailView.as_view(), name="owner-activity-detail"),
    path("owner-activities/<int:pk>/edit/", OwnerContributionDistributionUpdateView.as_view(), name="owner-activity-edit"),
    path("owner-activities/<int:pk>/archive/", OwnerContributionDistributionArchiveView.as_view(), name="owner-activity-archive"),
    path("owner-statements/", OwnerStatementView.as_view(), name="owner-statement"),
    path("owner-statements/export/", OwnerStatementExportView.as_view(), name="owner-statement-export"),
    path("pending-sync/", OwnerPendingSyncReportView.as_view(), name="owner-activity-pending-sync"),
    path("rent-roll/", RentRollReportView.as_view(), name="rent-roll-report"),
    path("tenant-ledger/", TenantLedgerReportView.as_view(), name="tenant-ledger-report"),
    path("delinquency/", DelinquencyReportView.as_view(), name="delinquency-report"),
    path("property-income-expense/", PropertyIncomeExpenseReportView.as_view(), name="property-income-expense-report"),
    path("owner-statements/report/", OwnerStatementReportView.as_view(), name="owner-statement-report"),
    path("security-deposit-ledger/", SecurityDepositLedgerReportView.as_view(), name="security-deposit-ledger-report"),
    path("management-fee-expense-summary/", ManagementFeeExpenseSummaryReportView.as_view(), name="management-fee-expense-summary-report"),
    path("maintenance-expense-summary/", MaintenanceExpenseSummaryReportView.as_view(), name="maintenance-expense-summary-report"),
    path("ledgeros/chart-of-accounts/", LedgerOSChartOfAccountsReportView.as_view(), name="ledgeros-chart-of-accounts-report"),
    path("ledgeros/trial-balance/", LedgerOSTrialBalanceReportView.as_view(), name="ledgeros-trial-balance-report"),
    path("ledgeros/profit-and-loss/", LedgerOSProfitAndLossReportView.as_view(), name="ledgeros-profit-and-loss-report"),
    path("ledgeros/balance-sheet/", LedgerOSBalanceSheetReportView.as_view(), name="ledgeros-balance-sheet-report"),
    path("ledgeros/period-summary/", LedgerOSPeriodSummaryReportView.as_view(), name="ledgeros-period-summary-report"),
    path("ledgeros/tax-summary/", LedgerOSTaxSummaryReportView.as_view(), name="ledgeros-tax-summary-report"),
    path("ledgeros/invoice-status/", LedgerOSInvoiceStatusReportView.as_view(), name="ledgeros-invoice-status-report"),
    path("ledgeros/bill-status/", LedgerOSBillStatusReportView.as_view(), name="ledgeros-bill-status-report"),
    path("ledgeros/payment-status/", LedgerOSPaymentStatusReportView.as_view(), name="ledgeros-payment-status-report"),
    path("ledgeros/bank-balances/", LedgerOSBankBalancesReportView.as_view(), name="ledgeros-bank-balances-report"),
    path("ledgeros/reconciliation-status/", LedgerOSReconciliationStatusReportView.as_view(), name="ledgeros-reconciliation-status-report"),
    path("ledgeros/audit-drilldown/", LedgerOSAuditDrilldownReportView.as_view(), name="ledgeros-audit-drilldown-report"),
]
