# Generated by Django 5.0.14 on 2026-06-15 23:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgeros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLedgerSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('validated', 'Validated'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('ledgeros_entity_id', models.CharField(blank=True, default='', max_length=255)),
                ('ledgeros_entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('ledgeros_accounting_period_id', models.CharField(blank=True, default='', max_length=255)),
                ('ledgeros_accounting_period_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_ledgeros_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_ledgeros_health_check_healthy', models.BooleanField(default=False)),
                ('last_ledgeros_health_check_payload', models.JSONField(blank=True, null=True)),
                ('last_setup_smoke_at', models.DateTimeField(blank=True, null=True)),
                ('last_setup_smoke_healthy', models.BooleanField(default=False)),
                ('last_setup_smoke_payload', models.JSONField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PropertyLedger setup',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='ledgerosconnectionsettings',
            name='health_path',
            field=models.CharField(default='/api/v1/health/', max_length=255),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('primary_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_properties', to='ledgeros.owner')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='ledgeros.property')),
            ],
            options={
                'ordering': ['property__name', 'name', 'id'],
                'unique_together': {('property', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField(blank=True, null=True)),
                ('rent_effective_date', models.DateField(blank=True, null=True)),
                ('base_monthly_rent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('base_monthly_rent_currency', models.CharField(default='USD', max_length=3)),
                ('deposit_required_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_required_currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='ledgeros.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='ledgeros.unit')),
            ],
            options={
                'ordering': ['-lease_start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLedgerAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_key', models.CharField(choices=[('operating_bank_account', 'Operating bank account'), ('undeposited_funds', 'Undeposited funds'), ('accounts_receivable', 'Accounts receivable'), ('accounts_payable', 'Accounts payable'), ('rental_income', 'Rental income'), ('repairs_and_maintenance_expense', 'Repairs and maintenance expense'), ('tenant_security_deposits_liability', 'Tenant security deposits liability'), ('owner_contributions_equity', 'Owner contributions equity'), ('owner_distributions_equity', 'Owner distributions equity'), ('credit_card_liability', 'Credit card liability'), ('mortgage_or_loan_liability', 'Mortgage or loan liability'), ('interest_expense', 'Interest expense'), ('principal_payment_mapping', 'Principal payment mapping')], max_length=64)),
                ('ledgeros_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('ledgeros_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('ledgeros_account_type', models.CharField(blank=True, default='', max_length=64)),
                ('is_required', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='ledgeros.propertyledgersetup')),
            ],
            options={
                'ordering': ['mapping_key', 'id'],
                'unique_together': {('setup', 'mapping_key')},
            },
        ),
    ]
