# Generated by Django 5.0.14 on 2026-06-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgeros', '0004_tenantcharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name', 'id'], 'verbose_name_plural': 'Properties'},
        ),
    ]
